NumPy = Numerical Python.
It's one of the fundamental libraries of the Python data ecosystem.

In [2]:
#Import numpy library
import numpy as np

In [5]:
#Python list vs NumPy array
numbers = [10, 20, 30, 40] #pyhon list
np_numbers = np.array([10, 20, 30, 40]) #numpy array
print(numbers)
print(np_numbers)
print(type(numbers))
print(type(np_numbers))

[10, 20, 30, 40]
[10 20 30 40]
<class 'list'>
<class 'numpy.ndarray'>


In [6]:
#Creating Arrays in numpy
#Exercise 1
numbers = np.array([10,20,30,40,50])
print(numbers)
print(type(numbers))
print(numbers.dtype)
print(numbers.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
(5,)


In [9]:
#NumPy's Superpower
#python list
numbers = [10, 20, 30]
numbers = numbers * 2
print(numbers)
#np array
#vectorized operation capability
np_numbers = np.array([10, 20, 30])
np_numbers = np_numbers * 2
print(np_numbers)

[10, 20, 30, 10, 20, 30]
[20 40 60]


In [13]:
#Exercise 2
prices = np.array([100,400,560,780])
#create discounted array 10%
discount = prices - (prices * 0.1)
print(discount)
#new price with add 20 to every price
new_price = prices + 20
print(new_price)
#double every price
doubled = prices * 2
print(doubled)

[ 90. 360. 504. 702.]
[120 420 580 800]
[ 200  800 1120 1560]


In [17]:
#Indexing and Slicing
#It's like python list indexing and slicing
scores = np.array([87,54,98,63,78,41])
#first element
print(scores[0])
#last element
print(scores[-1])
#slice
print(scores[1:4])

87
41
[54 98 63]


In [18]:
#Exercise 3
scores = np.array([85, 92, 78, 95, 88])
#fisrt score
print(scores[0])
#last score
print(scores[-1])
#first three scores
print(scores[:3])
#scores from index 2 onward
print(scores[2:])
#Every second score
print(scores[::2])

85
88
[85 92 78]
[78 95 88]
[85 78 88]


In [23]:
#NumPy Statistics
scores = np.array([85, 92, 78, 95, 88, 72, 90])
#calculate average
print(np.mean(scores))
#calculate max
print(np.max(scores))
#calculate min
print(np.min(scores))
#calculate sum
print(np.sum(scores))
#caculate standard deviation
print(np.std(scores))

85.71428571428571
95
72
600
7.534952568137482


In [27]:
#2D Arrays
sales = np.array([
    [100,200,300],
    [120,420,170],
    [90,510,100]
])
print(sales.shape) #three rows and three columns

(3, 3)


In [29]:
#Accessing elements
print(sales[0][1])

200


In [40]:
#Exercise 4
sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [120, 220, 320]
])
#the first row
print(sales[0])
#The second column.
print(sales[:,1])
#the last row
print(sales[-1])

[100 200 300]
[200 250 220]
[120 220 320]


In [46]:
#Mini Data Challenge
sales = np.array([
    [120, 150, 180, 200],
    [100, 130, 160, 190],
    [200, 220, 250, 280]
])
#Find the shape
print(sales.shape)
#Calculate total sales
print(np.sum(sales))
#Calculate the average sale
print(np.mean(sales))
#Find the highest sale
print(np.max(sales))
#Calculate the total sales for each product
print(np.sum(sales, axis=1))
#calculate total for each month.
print(np.sum(sales, axis=0))

(3, 4)
2180
181.66666666666666
280
[650 580 950]
[420 500 590 670]
