In [4]:
#Review
#import numpy
import numpy as np
#create a 2D numpy array
sales = np.array([
    [120, 150, 180, 200, 220],
    [100, 130, 160, 190, 210],
    [200, 220, 250, 280, 300]
])
print(sales.shape) #dimension
print(sales.ndim) #number of dimension
print(sales.size) #total number of elements

(3, 5)
2
15


In [47]:
#indexing and slicing
#Pattern is array[rows, columns]
#first row
print(sales[0])
#first column
print(sales[:,0]) #means all rows and column number 0

[120 150 180 200 220 250]
[120 100 200  80]


In [11]:
#Exercise 1
#product A, first three months
print(sales[0,:3])
#product A and B, march through may
print(sales[0:1,2:])

[120 150 180]
[[180 200 220]]


In [16]:
#Boolean Filtering
print(sales > 200) #return an array of true or false as result of comparison every element
print()
print(sales[sales > 200]) #return only values that is greater than 200

[[False False False False  True]
 [False False False False  True]
 [False  True  True  True  True]]

[220 210 220 250 280 300]


In [18]:
#Exercise 2
#find all sales greater than 220
print(sales[sales > 220])
#find all sales less than 150
print(sales[sales < 150])

[250 280 300]
[120 100 130]


In [21]:
#Exercise 3
#Boolean filtering and statistics
print(np.mean(sales[sales > 200]))

246.66666666666666


In [48]:
#Axis and Aggregation
sales = np.array([
    [120, 150, 180, 200, 220],
    [100, 130, 160, 190, 210],
    [200, 220, 250, 280, 300]
])
#total
print(np.sum(sales))
#total for each product
print(np.sum(sales,axis=1))

2910
[ 870  790 1250]


In [24]:
#total for each month
print(np.sum(sales,axis=0))

[420 500 590 670 730]


In [31]:
#Exercise 4
#calculate average monthly for each product
print(np.mean(sales,axis=1))
print(np.mean(sales,axis=0))
#find highest sales for each product
print(np.max(sales,axis=1))
#find highest sales for each month
print(np.max(sales,axis=0))

[174. 158. 250.]
[140.         166.66666667 196.66666667 223.33333333 243.33333333]
[220 210 300]
[200 220 250 280 300]


In [35]:
#Reshaping
#use arrange(start,finish) to create np array
numbers = np.arange(1,13)
print(numbers)
print(numbers.shape)
#reshape array
matrix = numbers.reshape(3,4)
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
#Exercise 5
numbers = np.arange(1, 21)
#reshape it 4 rows and 5 columns matrix
matrix = numbers.reshape(4,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [45]:
#Real Data Analysis challenge
#monthly sales for products as above scheme
sales = np.array([
    [120, 150, 180, 200, 220, 250],
    [100, 130, 160, 190, 210, 230],
    [200, 220, 250, 280, 300, 320],
    [80,  110, 140, 170, 190, 210]
])
#explore sales
print(sales.shape)
print(sales.ndim)
print(sales.size)
#calculate total sales for each produc
print(np.sum(sales,axis=1))
#which product has highest total sales
product_total = np.max(sales,axis=1)
np.argmax(product_total) 
#calculate the average monthly for each product
print(np.mean(sales,axis=1))
#find all sales greater than 250
print(sales[sales > 250])
#find the average of all sales greter than 250
print(np.mean(sales[sales > 250]))
#which month has highest total sales
month_sale = np.sum(sales, axis=0)
print(np.argmax(month_sale))

(4, 6)
2
24
[1120 1020 1570  900]
[186.66666667 170.         261.66666667 150.        ]
[280 300 320]
300.0
5
